version: '3.3'

volumes:
  postgres_data_database:

services:

  database:
    image: postgres:latest
    volumes:
      - postgres_data_database:/var/lib/postgresql/data/
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    expose:
      - ${DATABASE_PORT}

  backend:
    image: backend:latest
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    env_file: .env
    restart: on-failure
    depends_on:
      - database
    entrypoint: [ "sh", "-c" ]
    command: [ "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 80" ]
